TORCHDYNAMO_DISABLE=1 OMP_NUM_THREADS=1 CUDA_VISIBLE_DEVICES=2,3 nnUNetv2_train 106 2d 0 -p nnUNetPlans -tr nnUNetTrainerFGSM -num_gpus 2
TORCHDYNAMO_DISABLE=1 OMP_NUM_THREADS=1 CUDA_VISIBLE_DEVICES=2,3 nnUNetv2_train 106 2d 1 -p nnUNetPlans -tr nnUNetTrainerFGSM -num_gpus 2
TORCHDYNAMO_DISABLE=1 OMP_NUM_THREADS=1 CUDA_VISIBLE_DEVICES=2,3 nnUNetv2_train 106 2d 2 -p nnUNetPlans -tr nnUNetTrainerFGSM -num_gpus 2
TORCHDYNAMO_DISABLE=1 OMP_NUM_THREADS=1 CUDA_VISIBLE_DEVICES=2,3 nnUNetv2_train 106 2d 3 -p nnUNetPlans -tr nnUNetTrainerFGSM -num_gpus 2
TORCHDYNAMO_DISABLE=1 OMP_NUM_THREADS=1 CUDA_VISIBLE_DEVICES=2,3 nnUNetv2_train 106 2d 0 -p nnUNetPlans -tr nnUNetTrainerFGSM -num_gpus 2

